[project]
name = "ErisPulse-QQBotAdapter"
version = "5.0.0"
description = "ErisPulse的QQ官方机器人适配模块"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [ { name = "wsu2059", email = "wsu2059@qq.com" } ]
dependencies = [
    "ErisPulse>=2.8.0-dev.1",
    "cryptography>=41.0",
]

[project.urls]
"homepage" = "https://github.com/ErisPulse/ErisPulse-QQBotAdapter"

[project.entry-points."erispulse.adapter"]
qqbot = "QQBotAdapter:QQBotAdapter"

[tool.setuptools.packages.find]
include = [ "QQBotAdapter" ]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
